#!/usr/bin/env bash
# Affiche les nombres de 1 à 20 avec messages spéciaux pour certaines itérations
i=1
while [ $i -le 20 ]; do
  case $i in
    4) echo "$i"; echo "bad luck from China" ;;
    9) echo "$i"; echo "bad luck from Japan" ;;
    17) echo "$i"; echo "bad luck from Italy" ;;
    *) echo "$i" ;;
  esac
  ((i++))
done
